export {HomeAbout} from './HomeAbout'
export { HomeProjects } from './HomeProjects'
export {HomeHero} from './HomeHero'
export {HomeBlog} from './HomeBlog'
export { HomeLab } from './HomeLab'
export { HomeContactMe } from './HomeContactMe'